mysql:
  config:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "123456"
    database: "test"
  cconfig:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "12345678"
    database: "test"